<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PetusLauncher</AssemblyName>
    <RootNamespace>PetusLauncher</RootNamespace>
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
    <Version>2.2.0</Version>
    <!-- Custom protocol + deep links handled via single-instance pipe -->
  </PropertyGroup>

  <ItemGroup>
    <None Update="assets\icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\icon.png" />
    <EmbeddedResource Include="assets\petusmc-banner.png" />
    <EmbeddedResource Include="assets\petusmc-icon.png" />
  </ItemGroup>

</Project>
